replicaCount: 1

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/parking
  port: 80

selector:
  app: parking

image:
  name: parking-service
  tag: 2

config:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secret:
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo

migrations:
  image:
    name: parking-migrations
    tag: 2
  config:
    POSTGRES_DB: demo
    POSTGRES_HOST: postgres
    POSTGRES_USER: demo
    POSTGRES_PASSWORD: demo