apiVersion: apps/v1
kind: Deployment
metadata:
  name: guests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guests
  template:
    metadata:
      labels:
        app: guests
    spec:
      initContainers:
        - name: run-migrations
          image: guests-migrations:2
          command: [ "npx", "knex", "migrate:latest" ]
          envFrom:
            - configMapRef:
                name: guests-config
            - secretRef:
                name: guests-secret
      containers:
        - image: guests-service:2
          imagePullPolicy: Never
          name: guests
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: guests-config
            - secretRef:
                name: guests-secret