apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      initContainers:
        - name: run-migrations
          image: rooms-migrations:2
          command: [ "npx", "knex", "migrate:latest" ]
          envFrom:
            - configMapRef:
                name: rooms-config
            - secretRef:
                name: rooms-secret
      containers:
        - image: rooms-service:2 #docker build ... -> build project and push on docker hub, after he download.
          imagePullPolicy: Never #Set 'never', because Docker Hub restricted access from Donetsk region, and
          name: rooms
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: rooms-config
            - secretRef:
                name: rooms-secret
