apiVersion: apps/v1
kind: Deployment
metadata:
  name: employers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employers
  template:
    metadata:
      labels:
        app: employers
    spec:
      containers:
        - image: decel337/employers
          imagePullPolicy: Never
          name: employers
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: employers-service-config
            - secretRef:
                name: employers-service-secret
          env:
            - name: DB_URL
              value: "$(DB_DIALECT)://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"
