apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking
  template:
    metadata:
      labels:
        app: parking
    spec:
      initContainers:
        - name: run-migrations
          image: parking-migrations:2
          command: [ "npx", "knex", "migrate:latest" ]
          envFrom:
            - configMapRef:
                name: parking-config
            - secretRef:
                name: parking-secret
      containers:
        - image: parking-service:2 #docker build ... -> build project and push on docker hub, after he download.
          imagePullPolicy: Never #Set 'never', because Docker Hub restricted access from Donetsk region, and
          name: parking
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: parking-config
            - secretRef:
                name: parking-secret