postgresql:
  fullnameOverride: postgres
  auth:
    username: "demo"
    password: "demo"
    database: "demo"
  persistence:
    size: 5Gi
    mountPath: /var/lib/postgresql/data

kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      patch:
        podAnnotations:
          sidecar.istio.io/inject: "false"