apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff
  template:
    metadata:
      labels:
        app: staff
    spec:
      initContainers:
        - name: run-migrations
          image: staff-migrations:2
          command: [ "npx", "knex", "migrate:latest" ]
          envFrom:
            - configMapRef:
                name: staff-config
            - secretRef:
                name: staff-secret
      containers:
        - image: staff-service:2
          imagePullPolicy: Never
          name: staff
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: staff-config
            - secretRef:
                name: staff-secret