replicaCount: 1

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/staff
  port: 80

selector:
  app: staff

image:
  name: staff-service
  tag: 2

config:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secret:
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo

migrations:
  image:
    name: staff-migrations
    tag: 2
  config:
    POSTGRES_DB: demo
    POSTGRES_HOST: postgres
    POSTGRES_USER: demo
    POSTGRES_PASSWORD: demo

virtual:
  timeout: 5s
  retries:
    attempts: 3
    retryOn: 5xx
    perTryTimeout: 5s

destination:
  consecutive5xxErrors: 5
  interval: 10s
  baseEjectionTime: 30s
  maxEjectionPercent: 80